### ISSUE TITLE
Roadmap 0.3.0

### ISSUE THREAD

**Issue by boennemann** [excellenteasy/bradypodion#37]
I had to close #25, which doesn't mean that there's no need to implement all the things mentioned in there.
Quite the opposite, but we need to push all those features to 0.4.0 and release a slimmer 0.3.0 now.
- [ ] ~~Angular 1.2.0(rc) compat (esp. animations)~~
- [ ] ~~Convert tests to [Protractor](https://github.com/angular/protractor)~~
- [x] Update and consolidate all dependencies ~~front(aka bower) &~~ back(aka npm)
- [x] Use generator-angular based build process #36
- [x] Convert existing demos to new demo app
- [x] migrate tabbar, detail disclosure and other fixes/features from old 0.3.0 branch to new bp structure
- [x] ~~deprecate old iOS or at least~~ 0.3.0 should be the last release that supports it (talking styles only here)

**Comment by davidpfahler** [comment]
> we need to push all those features to 0.4.0 and release a slimmer 0.3.0 now

:+1: 

I want to move "Angular 1.2.0(rc) compat (esp. animations)" from the TODO list to 0.4.0 as well. We should wait until 1.2.0 is officially released and out for a couple of weeks (bugs!).

**Comment by boennemann** [comment]
The already existing segmentedControl will be a candidate for 0.4.0, as it only implements iOS7 styling. In foresight of the ios6 deprecation I'll push it out to 0.4.0

**Comment by davidpfahler** [comment]
:+1:
