### ISSUE TITLE
Navbar, Toolbar and Slide Transtition

### ISSUE THREAD

**Issue by boennemann** [excellenteasy/bradypodion#56]
- [x] test current navbar code #57 
- [x] introduce a way to use icons in the ios navbar #60 
- [x] implement toolbar/action overflow #61
- [x] automatically create toolbar/action overflow from within the navbar #64 
- [x] make slide transition independent from navbar #59 
- [x] make navbar state-aware #68
- [x] transition correctly  #69
